import type { Copy } from "../../copy.en";

export const auth: Copy["auth"] = {
    signIn: {
      modes: {
        signIn: {
          eyebrow: "ClauseCompass mein swagat hai",
          heading: "Apna document kholne ke liye sign in karein",
          lead: "ClauseCompass document usi account ke liye kholta hai jisse use upload kiya gaya, isliye use jaanna hota hai ki aapka account kaun sa hai. Google account ya email aur password, dono chalenge.",
        },
        create: {
          eyebrow: "Apna account banayein",
          heading: "Saaf samajh",
          accent: "yahin se shuru hoti hai.",
          lead: "Account se ClauseCompass ek reader ke documents ko doosre ke documents se alag pehchanta hai. Email aur password se ek banayein, ya apne Google account se aage badhein.",
        },
        reset: {
          eyebrow: "Password bhool gaye?",
          heading: "Email par reset link paayein",
          lead: "Apne account ka email address likhein. Reset email mein naya password chunne ka link aayega; uske baad yahan pehle ki tarah sign in karein.",
        },
      },
      points: {
        signIn: [
          { title: "Aapke documents, aapke account ke neeche", line: "Har document usi account ke liye khulta hai jisse use upload kiya gaya." },
          { title: "Saral, saaf padhai", line: "Har clause aasan shabdon mein, saath mein uska source text." },
          { title: "Aam logon ke liye bana", line: "Aasan bhasha. Behtar faisle." },
        ],
        create: [
          { title: "Ek account, aapke documents", line: "Isi se ClauseCompass aapke documents ko kisi aur reader ke documents se alag pehchanta hai." },
          { title: "Saaf explanations", line: "Har clause ke liye aasan shabd, saath mein source text." },
          { title: "Sirf kuch samay ke liye rakha jaata hai", line: "Document tab khatam hota hai jab aap use delete karein, ya jab retention window beet jaaye." },
        ],
      },
      google: "Google se aage badhein",
      or: "ya email se",
      email: "Email",
      emailPlaceholder: "aap@example.com",
      password: "Password",
      passwordPlaceholder: { signIn: "Apna password likhein", create: "Ek password banayein" },
      passwordHint: "Kam se kam 6 characters.",
      showPassword: "Password dikhayein",
      hidePassword: "Password chhupayein",
      submit: { signIn: "Sign in karein", create: "Account banayein", reset: "Reset email bhejein" },
      working: "Ek pal…",
      toCreate: "Naye hain? Account banayein",
      toSignIn: { question: "Pehle se account hai?", action: "Sign in karein" },
      toSignInFromReset: "Sign in par wapas jaayein",
      toReset: "Password bhool gaye?",
      resetSent: (email: string) => `${email} par reset email bheja gaya hai. Uska link kholkar naya password chunein, phir yahan sign in karein.`,
      note: "Sign in karne se document kitne samay tak rakha jaata hai, yeh nahi badalta. Document aur usse taiyar ki gayi har cheez tab bhi khatam hoti hai jab aap use delete karein, ya jab retention window beet jaaye; account bas itna batata hai ki woh aapke hain.",
      back: "Shuruaat par wapas jaayein",
      done: "Sign in ho gaya. Aapko aapke document tak le ja rahe hain…",
    },
    header: {
      signIn: "Sign in",
      signOut: "Sign out",
      signedInAs: (name: string) => `${name} ke roop mein sign in`,
      signingOut: "Sign out ho raha hai…",
    },
    errors: {
      emailRequired: "Apne account ka email address likhein.",
      passwordRequired: "Apna password likhein.",
      "popup-blocked": "Browser ne Google sign-in window rok di. Is page ke liye pop-ups allow karein, ClauseCompass ko alag tab mein kholein, ya email se sign in karein.",
      "popup-closed": "Google sign-in window poori hone se pehle band ho gayi. Jab taiyar hon, phir se try karein.",
      "unauthorized-domain": "ClauseCompass ke is address par Google sign-in abhi chalu nahi hai. Email se sign in karein, ya baad mein phir try karein.",
      "provider-off": "Sign in karne ka yeh tareeka ClauseCompass ke liye abhi chalu nahi hai. Doosra tareeka try karein.",
      "wrong-password": "Yeh email aur password yahan kisi account se mel nahi khaate. Dono check karke phir try karein, ya password reset karein.",
      "no-account": "Is email se abhi koi account nahi hai. Email check karein, ya account banayein.",
      "email-in-use": "Is email se account pehle se hai. Sign in karein, ya password reset karein.",
      "weak-password": "Thoda lamba password chunein: kam se kam 6 characters.",
      "bad-email": "Yeh email address jaisa nahi lagta. Check karke phir try karein.",
      "too-many": "Lagataar bahut baar try ho gaya. Kuch minute rukein, phir try karein.",
      disabled: "Yeh account disable kar diya gaya hai. Agar yeh anpekshit hai, to ClauseCompass ki is copy ko chalane waale se sampark karein.",
      offline: "Sign-in Google tak nahi pahunch saka. Apna connection check karke phir try karein.",
      "not-configured": "ClauseCompass ki is copy par sign-in set up nahi hai. Ise chalane waale ko sign-in configuration jodni hogi.",
      unknown: "Sign-in poora nahi hua. Thodi der mein phir try karein.",
    },
  };
