/**
 * Query expansion for lay and Hinglish wording. People ask about "rent" and
 * "the landlord"; a leave-and-licence agreement says "licence fee" and
 * "Licensor". Each entry maps a word a reader might type to the words a
 * contract tends to use; expansions score at a fraction of the typed word's
 * weight so that an exact match always wins over a guessed one. Data, not
 * code: extend it when a sample question misses its clause.
 */
export const QUERY_SYNONYMS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  // --- rental ---
  rent: ["licence fee", "monthly"],
  rental: ["licence fee", "monthly"],
  landlord: ["licensor", "lessor", "owner"],
  owner: ["licensor", "lessor", "landlord"],
  tenant: ["licensee", "lessee"],
  flat: ["premises", "apartment", "house"],
  house: ["premises", "flat"],
  home: ["premises", "flat", "house"],
  back: ["refund", "return", "repay"],
  refund: ["return", "repay", "forfeit"],
  vacate: ["hand over", "possession", "keys"],
  move: ["vacate", "possession"],
  leave: ["vacate", "terminate", "resign", "exit"],
  quit: ["resign", "terminate", "notice"],
  break: ["terminate", "lock-in", "breach"],
  lease: ["licence", "agreement", "tenancy"],
  early: ["lock-in", "earlier", "prior"],
  midway: ["lock-in", "earlier", "prior"],
  extend: ["renew", "extension", "renewal"],
  renew: ["extend", "extension", "renewal"],
  increase: ["escalation", "revised", "revision", "hike"],
  hike: ["increase", "escalation", "revised"],
  fine: ["penalty", "late fee", "charge", "damages"],
  penalty: ["damages", "late fee", "charge", "forfeit"],
  repair: ["maintenance", "maintain", "replacement"],
  maintenance: ["repair", "society"],
  bill: ["charges", "utilities", "electricity", "society"],
  bills: ["charges", "utilities", "electricity", "society"],
  guest: ["guests", "reside", "sub-let"],
  furniture: ["fittings", "fixtures", "schedule"],
  visit: ["enter", "inspect", "inspection"],
  enter: ["inspect", "inspection", "entry"],
  inspection: ["enter", "inspect"],
  paint: ["painting", "deduct", "deductions"],
  // --- employment ---
  job: ["employment", "position", "role"],
  fired: ["terminate", "dismiss", "misconduct"],
  fire: ["terminate", "dismiss"],
  sacked: ["terminate", "dismiss", "misconduct"],
  resign: ["terminate", "notice", "resignation"],
  salary: ["remuneration", "compensation", "ctc", "pay"],
  pay: ["payment", "salary", "fee"],
  paid: ["payment", "salary", "payable"],
  bonus: ["variable", "incentive", "discretionary"],
  holiday: ["leave"],
  holidays: ["leave"],
  vacation: ["leave"],
  sick: ["leave", "medical"],
  overtime: ["hours", "working"],
  wfh: ["remote", "office", "place of work"],
  transfer: ["relocate", "place of work", "office"],
  sign: ["execute", "execution", "accept", "acceptance"],
  poach: ["solicit", "solicitation"],
  competitor: ["competes", "compete", "competing", "business"],
  competitors: ["competes", "compete", "competing", "business"],
  leaving: ["ends", "terminate", "resign", "exit"],
  left: ["ends", "terminate", "resign", "exit"],
  bond: ["training", "repay", "serve", "minimum period", "cost"],
  buyout: ["lieu", "notice", "shorter"],
  // --- disputes ---
  sue: ["court", "arbitration", "dispute", "jurisdiction"],
  court: ["jurisdiction", "arbitration", "dispute"],
  lawyer: ["dispute", "arbitration", "legal"],
  // --- nda ---
  secret: ["confidential", "confidentiality", "disclose"],
  nda: ["confidential", "confidentiality", "disclose"],
  share: ["disclose", "disclosure"],
  // --- Hinglish ---
  kiraya: ["rent", "licence fee", "monthly"],
  kiraye: ["rent", "licence fee", "monthly"],
  kiraaya: ["rent", "licence fee", "monthly"],
  makan: ["premises", "flat", "house"],
  makaan: ["premises", "flat", "house"],
  ghar: ["premises", "house", "flat", "home"],
  malik: ["landlord", "licensor", "owner"],
  maalik: ["landlord", "licensor", "owner"],
  kirayedar: ["tenant", "licensee"],
  paisa: ["money", "payment", "fee", "amount"],
  paise: ["money", "payment", "fee", "amount"],
  tankhwah: ["salary", "remuneration"],
  tankha: ["salary", "remuneration"],
  naukri: ["employment", "job"],
  nokri: ["employment", "job"],
  kaam: ["work", "duties", "employment"],
  chhutti: ["leave", "holiday"],
  chutti: ["leave", "holiday"],
  jurmana: ["penalty", "fine", "late fee", "damages"],
  jurmaana: ["penalty", "fine", "late fee", "damages"],
  wapas: ["refund", "return", "repay"],
  vapas: ["refund", "return", "repay"],
  wapis: ["refund", "return", "repay"],
  khali: ["vacate", "possession"],
  khaali: ["vacate", "possession"],
  todna: ["terminate", "breach", "break"],
  todh: ["terminate", "breach", "break"],
  chhodna: ["resign", "terminate", "vacate"],
  chodna: ["resign", "terminate", "vacate"],
  din: ["day", "days"],
  dino: ["day", "days"],
  dinon: ["day", "days"],
  mahina: ["month", "months"],
  mahine: ["month", "months"],
  maheena: ["month", "months"],
  saal: ["year", "years"],
  hafta: ["week", "weeks"],
  hafte: ["week", "weeks"],
  samay: ["time", "period", "term"],
  waqt: ["time", "period", "term"],
  tarikh: ["date", "day"],
  tareekh: ["date", "day"],
  shart: ["condition", "conditions", "terms"],
  sharten: ["condition", "conditions", "terms"],
  kagaz: ["document", "agreement"],
  dastavez: ["document", "agreement"],
  dastakhat: ["sign", "signed", "execution", "acceptance"],
  hastakshar: ["sign", "signed", "execution", "acceptance"],
  badhana: ["increase", "escalation", "revision", "extend"],
  badhaya: ["increase", "escalation", "revision"],
  badhega: ["increase", "escalation", "revision"],
  bimari: ["sick", "medical", "leave"],
  bimar: ["sick", "medical", "leave"],
  adalat: ["court", "jurisdiction", "arbitration", "dispute"],
  bijli: ["electricity", "utilities", "charges", "society"],
  pani: ["water", "utilities", "charges"],
  paani: ["water", "utilities", "charges"],
  janwar: ["pets", "pet"],
  kutta: ["pets", "pet", "dog"],
  billi: ["pets", "pet", "cat"],
  mehmaan: ["guests", "guest", "reside"],
  mehman: ["guests", "guest", "reside"],
  advance: ["deposit", "security deposit"],
  aa: ["enter", "inspect", "visit"],
  aana: ["enter", "inspect", "visit"],
  aaye: ["enter", "inspect", "visit"],
  aayega: ["enter", "inspect", "visit"],
  aake: ["enter", "inspect", "visit"],
  ghusna: ["enter", "inspect", "entry"],
  // --- Hindi (Devanagari is not stemmed, so common inflections are listed) ---
  किराया: ["rent", "licence fee", "monthly"],
  किराये: ["rent", "licence fee", "monthly"],
  मकान: ["premises", "flat", "house"],
  घर: ["premises", "house", "flat", "home"],
  मालिक: ["landlord", "licensor", "owner"],
  किरायेदार: ["tenant", "licensee"],
  जमा: ["deposit", "security deposit"],
  डिपॉजिट: ["deposit", "security deposit"],
  नोटिस: ["notice"],
  वापस: ["refund", "return", "repay"],
  खाली: ["vacate", "possession"],
  तोड़ना: ["terminate", "breach", "break"],
  तोड़: ["terminate", "breach", "break"],
  छोड़ना: ["resign", "terminate", "vacate"],
  छोड़: ["resign", "terminate", "vacate"],
  नौकरी: ["employment", "job"],
  काम: ["work", "duties", "employment"],
  तनख्वाह: ["salary", "remuneration"],
  वेतन: ["salary", "remuneration"],
  सैलरी: ["salary", "remuneration"],
  बोनस: ["bonus", "variable", "incentive"],
  छुट्टी: ["leave", "holiday"],
  छुट्टियाँ: ["leave", "holiday"],
  जुर्माना: ["penalty", "fine", "late fee", "damages"],
  पैसा: ["money", "payment", "fee", "amount"],
  पैसे: ["money", "payment", "fee", "amount"],
  दिन: ["day", "days"],
  दिनों: ["day", "days"],
  महीना: ["month", "months"],
  महीने: ["month", "months"],
  साल: ["year", "years"],
  हफ्ता: ["week", "weeks"],
  हफ्ते: ["week", "weeks"],
  समय: ["time", "period", "term"],
  तारीख: ["date", "day"],
  शर्त: ["condition", "conditions", "terms"],
  शर्तें: ["condition", "conditions", "terms"],
  कागज़: ["document", "agreement"],
  कागज: ["document", "agreement"],
  दस्तावेज़: ["document", "agreement"],
  दस्तावेज: ["document", "agreement"],
  हस्ताक्षर: ["sign", "signed", "execution", "acceptance"],
  दस्तखत: ["sign", "signed", "execution", "acceptance"],
  साइन: ["sign", "signed", "execution", "acceptance"],
  बढ़ाना: ["increase", "escalation", "revision", "extend"],
  बढ़ेगा: ["increase", "escalation", "revision"],
  बढ़ाया: ["increase", "escalation", "revision"],
  अदालत: ["court", "jurisdiction", "arbitration", "dispute"],
  कोर्ट: ["court", "jurisdiction", "arbitration", "dispute"],
  बिजली: ["electricity", "utilities", "charges", "society"],
  पानी: ["water", "utilities", "charges"],
  पालतू: ["pets", "pet"],
  कुत्ता: ["pets", "pet", "dog"],
  बिल्ली: ["pets", "pet", "cat"],
  मेहमान: ["guests", "guest", "reside"],
  बीमार: ["sick", "medical", "leave"],
  बीमारी: ["sick", "medical", "leave"],
  प्रोबेशन: ["probation"],
  आना: ["enter", "inspect", "visit"],
  आएगा: ["enter", "inspect", "visit"],
  गोपनीय: ["confidential", "confidentiality", "disclose"],
  गोपनीयता: ["confidential", "confidentiality", "disclose"],
});
